
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RequestFile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model RequestFile
 * 
 */
export type RequestFileModel = runtime.Types.Result.DefaultSelection<Prisma.$RequestFilePayload>

export type AggregateRequestFile = {
  _count: RequestFileCountAggregateOutputType | null
  _min: RequestFileMinAggregateOutputType | null
  _max: RequestFileMaxAggregateOutputType | null
}

export type RequestFileMinAggregateOutputType = {
  id: string | null
  requestId: string | null
  fileUrl: string | null
  fileType: string | null
  createdAt: Date | null
}

export type RequestFileMaxAggregateOutputType = {
  id: string | null
  requestId: string | null
  fileUrl: string | null
  fileType: string | null
  createdAt: Date | null
}

export type RequestFileCountAggregateOutputType = {
  id: number
  requestId: number
  fileUrl: number
  fileType: number
  createdAt: number
  _all: number
}


export type RequestFileMinAggregateInputType = {
  id?: true
  requestId?: true
  fileUrl?: true
  fileType?: true
  createdAt?: true
}

export type RequestFileMaxAggregateInputType = {
  id?: true
  requestId?: true
  fileUrl?: true
  fileType?: true
  createdAt?: true
}

export type RequestFileCountAggregateInputType = {
  id?: true
  requestId?: true
  fileUrl?: true
  fileType?: true
  createdAt?: true
  _all?: true
}

export type RequestFileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RequestFile to aggregate.
   */
  where?: Prisma.RequestFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestFiles to fetch.
   */
  orderBy?: Prisma.RequestFileOrderByWithRelationInput | Prisma.RequestFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RequestFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RequestFiles
  **/
  _count?: true | RequestFileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RequestFileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RequestFileMaxAggregateInputType
}

export type GetRequestFileAggregateType<T extends RequestFileAggregateArgs> = {
      [P in keyof T & keyof AggregateRequestFile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRequestFile[P]>
    : Prisma.GetScalarType<T[P], AggregateRequestFile[P]>
}




export type RequestFileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RequestFileWhereInput
  orderBy?: Prisma.RequestFileOrderByWithAggregationInput | Prisma.RequestFileOrderByWithAggregationInput[]
  by: Prisma.RequestFileScalarFieldEnum[] | Prisma.RequestFileScalarFieldEnum
  having?: Prisma.RequestFileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RequestFileCountAggregateInputType | true
  _min?: RequestFileMinAggregateInputType
  _max?: RequestFileMaxAggregateInputType
}

export type RequestFileGroupByOutputType = {
  id: string
  requestId: string
  fileUrl: string
  fileType: string
  createdAt: Date
  _count: RequestFileCountAggregateOutputType | null
  _min: RequestFileMinAggregateOutputType | null
  _max: RequestFileMaxAggregateOutputType | null
}

type GetRequestFileGroupByPayload<T extends RequestFileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RequestFileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RequestFileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RequestFileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RequestFileGroupByOutputType[P]>
      }
    >
  >



export type RequestFileWhereInput = {
  AND?: Prisma.RequestFileWhereInput | Prisma.RequestFileWhereInput[]
  OR?: Prisma.RequestFileWhereInput[]
  NOT?: Prisma.RequestFileWhereInput | Prisma.RequestFileWhereInput[]
  id?: Prisma.StringFilter<"RequestFile"> | string
  requestId?: Prisma.StringFilter<"RequestFile"> | string
  fileUrl?: Prisma.StringFilter<"RequestFile"> | string
  fileType?: Prisma.StringFilter<"RequestFile"> | string
  createdAt?: Prisma.DateTimeFilter<"RequestFile"> | Date | string
  request?: Prisma.XOR<Prisma.RequestScalarRelationFilter, Prisma.RequestWhereInput>
}

export type RequestFileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  request?: Prisma.RequestOrderByWithRelationInput
}

export type RequestFileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RequestFileWhereInput | Prisma.RequestFileWhereInput[]
  OR?: Prisma.RequestFileWhereInput[]
  NOT?: Prisma.RequestFileWhereInput | Prisma.RequestFileWhereInput[]
  requestId?: Prisma.StringFilter<"RequestFile"> | string
  fileUrl?: Prisma.StringFilter<"RequestFile"> | string
  fileType?: Prisma.StringFilter<"RequestFile"> | string
  createdAt?: Prisma.DateTimeFilter<"RequestFile"> | Date | string
  request?: Prisma.XOR<Prisma.RequestScalarRelationFilter, Prisma.RequestWhereInput>
}, "id">

export type RequestFileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.RequestFileCountOrderByAggregateInput
  _max?: Prisma.RequestFileMaxOrderByAggregateInput
  _min?: Prisma.RequestFileMinOrderByAggregateInput
}

export type RequestFileScalarWhereWithAggregatesInput = {
  AND?: Prisma.RequestFileScalarWhereWithAggregatesInput | Prisma.RequestFileScalarWhereWithAggregatesInput[]
  OR?: Prisma.RequestFileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RequestFileScalarWhereWithAggregatesInput | Prisma.RequestFileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RequestFile"> | string
  requestId?: Prisma.StringWithAggregatesFilter<"RequestFile"> | string
  fileUrl?: Prisma.StringWithAggregatesFilter<"RequestFile"> | string
  fileType?: Prisma.StringWithAggregatesFilter<"RequestFile"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RequestFile"> | Date | string
}

export type RequestFileCreateInput = {
  id?: string
  fileUrl: string
  fileType?: string
  createdAt?: Date | string
  request: Prisma.RequestCreateNestedOneWithoutFilesInput
}

export type RequestFileUncheckedCreateInput = {
  id?: string
  requestId: string
  fileUrl: string
  fileType?: string
  createdAt?: Date | string
}

export type RequestFileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  request?: Prisma.RequestUpdateOneRequiredWithoutFilesNestedInput
}

export type RequestFileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RequestFileCreateManyInput = {
  id?: string
  requestId: string
  fileUrl: string
  fileType?: string
  createdAt?: Date | string
}

export type RequestFileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RequestFileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requestId?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RequestFileListRelationFilter = {
  every?: Prisma.RequestFileWhereInput
  some?: Prisma.RequestFileWhereInput
  none?: Prisma.RequestFileWhereInput
}

export type RequestFileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RequestFileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RequestFileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RequestFileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestId?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RequestFileCreateNestedManyWithoutRequestInput = {
  create?: Prisma.XOR<Prisma.RequestFileCreateWithoutRequestInput, Prisma.RequestFileUncheckedCreateWithoutRequestInput> | Prisma.RequestFileCreateWithoutRequestInput[] | Prisma.RequestFileUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.RequestFileCreateOrConnectWithoutRequestInput | Prisma.RequestFileCreateOrConnectWithoutRequestInput[]
  createMany?: Prisma.RequestFileCreateManyRequestInputEnvelope
  connect?: Prisma.RequestFileWhereUniqueInput | Prisma.RequestFileWhereUniqueInput[]
}

export type RequestFileUncheckedCreateNestedManyWithoutRequestInput = {
  create?: Prisma.XOR<Prisma.RequestFileCreateWithoutRequestInput, Prisma.RequestFileUncheckedCreateWithoutRequestInput> | Prisma.RequestFileCreateWithoutRequestInput[] | Prisma.RequestFileUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.RequestFileCreateOrConnectWithoutRequestInput | Prisma.RequestFileCreateOrConnectWithoutRequestInput[]
  createMany?: Prisma.RequestFileCreateManyRequestInputEnvelope
  connect?: Prisma.RequestFileWhereUniqueInput | Prisma.RequestFileWhereUniqueInput[]
}

export type RequestFileUpdateManyWithoutRequestNestedInput = {
  create?: Prisma.XOR<Prisma.RequestFileCreateWithoutRequestInput, Prisma.RequestFileUncheckedCreateWithoutRequestInput> | Prisma.RequestFileCreateWithoutRequestInput[] | Prisma.RequestFileUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.RequestFileCreateOrConnectWithoutRequestInput | Prisma.RequestFileCreateOrConnectWithoutRequestInput[]
  upsert?: Prisma.RequestFileUpsertWithWhereUniqueWithoutRequestInput | Prisma.RequestFileUpsertWithWhereUniqueWithoutRequestInput[]
  createMany?: Prisma.RequestFileCreateManyRequestInputEnvelope
  set?: Prisma.RequestFileWhereUniqueInput | Prisma.RequestFileWhereUniqueInput[]
  disconnect?: Prisma.RequestFileWhereUniqueInput | Prisma.RequestFileWhereUniqueInput[]
  delete?: Prisma.RequestFileWhereUniqueInput | Prisma.RequestFileWhereUniqueInput[]
  connect?: Prisma.RequestFileWhereUniqueInput | Prisma.RequestFileWhereUniqueInput[]
  update?: Prisma.RequestFileUpdateWithWhereUniqueWithoutRequestInput | Prisma.RequestFileUpdateWithWhereUniqueWithoutRequestInput[]
  updateMany?: Prisma.RequestFileUpdateManyWithWhereWithoutRequestInput | Prisma.RequestFileUpdateManyWithWhereWithoutRequestInput[]
  deleteMany?: Prisma.RequestFileScalarWhereInput | Prisma.RequestFileScalarWhereInput[]
}

export type RequestFileUncheckedUpdateManyWithoutRequestNestedInput = {
  create?: Prisma.XOR<Prisma.RequestFileCreateWithoutRequestInput, Prisma.RequestFileUncheckedCreateWithoutRequestInput> | Prisma.RequestFileCreateWithoutRequestInput[] | Prisma.RequestFileUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.RequestFileCreateOrConnectWithoutRequestInput | Prisma.RequestFileCreateOrConnectWithoutRequestInput[]
  upsert?: Prisma.RequestFileUpsertWithWhereUniqueWithoutRequestInput | Prisma.RequestFileUpsertWithWhereUniqueWithoutRequestInput[]
  createMany?: Prisma.RequestFileCreateManyRequestInputEnvelope
  set?: Prisma.RequestFileWhereUniqueInput | Prisma.RequestFileWhereUniqueInput[]
  disconnect?: Prisma.RequestFileWhereUniqueInput | Prisma.RequestFileWhereUniqueInput[]
  delete?: Prisma.RequestFileWhereUniqueInput | Prisma.RequestFileWhereUniqueInput[]
  connect?: Prisma.RequestFileWhereUniqueInput | Prisma.RequestFileWhereUniqueInput[]
  update?: Prisma.RequestFileUpdateWithWhereUniqueWithoutRequestInput | Prisma.RequestFileUpdateWithWhereUniqueWithoutRequestInput[]
  updateMany?: Prisma.RequestFileUpdateManyWithWhereWithoutRequestInput | Prisma.RequestFileUpdateManyWithWhereWithoutRequestInput[]
  deleteMany?: Prisma.RequestFileScalarWhereInput | Prisma.RequestFileScalarWhereInput[]
}

export type RequestFileCreateWithoutRequestInput = {
  id?: string
  fileUrl: string
  fileType?: string
  createdAt?: Date | string
}

export type RequestFileUncheckedCreateWithoutRequestInput = {
  id?: string
  fileUrl: string
  fileType?: string
  createdAt?: Date | string
}

export type RequestFileCreateOrConnectWithoutRequestInput = {
  where: Prisma.RequestFileWhereUniqueInput
  create: Prisma.XOR<Prisma.RequestFileCreateWithoutRequestInput, Prisma.RequestFileUncheckedCreateWithoutRequestInput>
}

export type RequestFileCreateManyRequestInputEnvelope = {
  data: Prisma.RequestFileCreateManyRequestInput | Prisma.RequestFileCreateManyRequestInput[]
  skipDuplicates?: boolean
}

export type RequestFileUpsertWithWhereUniqueWithoutRequestInput = {
  where: Prisma.RequestFileWhereUniqueInput
  update: Prisma.XOR<Prisma.RequestFileUpdateWithoutRequestInput, Prisma.RequestFileUncheckedUpdateWithoutRequestInput>
  create: Prisma.XOR<Prisma.RequestFileCreateWithoutRequestInput, Prisma.RequestFileUncheckedCreateWithoutRequestInput>
}

export type RequestFileUpdateWithWhereUniqueWithoutRequestInput = {
  where: Prisma.RequestFileWhereUniqueInput
  data: Prisma.XOR<Prisma.RequestFileUpdateWithoutRequestInput, Prisma.RequestFileUncheckedUpdateWithoutRequestInput>
}

export type RequestFileUpdateManyWithWhereWithoutRequestInput = {
  where: Prisma.RequestFileScalarWhereInput
  data: Prisma.XOR<Prisma.RequestFileUpdateManyMutationInput, Prisma.RequestFileUncheckedUpdateManyWithoutRequestInput>
}

export type RequestFileScalarWhereInput = {
  AND?: Prisma.RequestFileScalarWhereInput | Prisma.RequestFileScalarWhereInput[]
  OR?: Prisma.RequestFileScalarWhereInput[]
  NOT?: Prisma.RequestFileScalarWhereInput | Prisma.RequestFileScalarWhereInput[]
  id?: Prisma.StringFilter<"RequestFile"> | string
  requestId?: Prisma.StringFilter<"RequestFile"> | string
  fileUrl?: Prisma.StringFilter<"RequestFile"> | string
  fileType?: Prisma.StringFilter<"RequestFile"> | string
  createdAt?: Prisma.DateTimeFilter<"RequestFile"> | Date | string
}

export type RequestFileCreateManyRequestInput = {
  id?: string
  fileUrl: string
  fileType?: string
  createdAt?: Date | string
}

export type RequestFileUpdateWithoutRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RequestFileUncheckedUpdateWithoutRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RequestFileUncheckedUpdateManyWithoutRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RequestFileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  fileUrl?: boolean
  fileType?: boolean
  createdAt?: boolean
  request?: boolean | Prisma.RequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["requestFile"]>

export type RequestFileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  fileUrl?: boolean
  fileType?: boolean
  createdAt?: boolean
  request?: boolean | Prisma.RequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["requestFile"]>

export type RequestFileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestId?: boolean
  fileUrl?: boolean
  fileType?: boolean
  createdAt?: boolean
  request?: boolean | Prisma.RequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["requestFile"]>

export type RequestFileSelectScalar = {
  id?: boolean
  requestId?: boolean
  fileUrl?: boolean
  fileType?: boolean
  createdAt?: boolean
}

export type RequestFileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "requestId" | "fileUrl" | "fileType" | "createdAt", ExtArgs["result"]["requestFile"]>
export type RequestFileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request?: boolean | Prisma.RequestDefaultArgs<ExtArgs>
}
export type RequestFileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request?: boolean | Prisma.RequestDefaultArgs<ExtArgs>
}
export type RequestFileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request?: boolean | Prisma.RequestDefaultArgs<ExtArgs>
}

export type $RequestFilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RequestFile"
  objects: {
    request: Prisma.$RequestPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    requestId: string
    fileUrl: string
    fileType: string
    createdAt: Date
  }, ExtArgs["result"]["requestFile"]>
  composites: {}
}

export type RequestFileGetPayload<S extends boolean | null | undefined | RequestFileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RequestFilePayload, S>

export type RequestFileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RequestFileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RequestFileCountAggregateInputType | true
  }

export interface RequestFileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RequestFile'], meta: { name: 'RequestFile' } }
  /**
   * Find zero or one RequestFile that matches the filter.
   * @param {RequestFileFindUniqueArgs} args - Arguments to find a RequestFile
   * @example
   * // Get one RequestFile
   * const requestFile = await prisma.requestFile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RequestFileFindUniqueArgs>(args: Prisma.SelectSubset<T, RequestFileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RequestFileClient<runtime.Types.Result.GetResult<Prisma.$RequestFilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RequestFile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RequestFileFindUniqueOrThrowArgs} args - Arguments to find a RequestFile
   * @example
   * // Get one RequestFile
   * const requestFile = await prisma.requestFile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RequestFileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RequestFileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RequestFileClient<runtime.Types.Result.GetResult<Prisma.$RequestFilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RequestFile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestFileFindFirstArgs} args - Arguments to find a RequestFile
   * @example
   * // Get one RequestFile
   * const requestFile = await prisma.requestFile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RequestFileFindFirstArgs>(args?: Prisma.SelectSubset<T, RequestFileFindFirstArgs<ExtArgs>>): Prisma.Prisma__RequestFileClient<runtime.Types.Result.GetResult<Prisma.$RequestFilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RequestFile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestFileFindFirstOrThrowArgs} args - Arguments to find a RequestFile
   * @example
   * // Get one RequestFile
   * const requestFile = await prisma.requestFile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RequestFileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RequestFileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RequestFileClient<runtime.Types.Result.GetResult<Prisma.$RequestFilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RequestFiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestFileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RequestFiles
   * const requestFiles = await prisma.requestFile.findMany()
   * 
   * // Get first 10 RequestFiles
   * const requestFiles = await prisma.requestFile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const requestFileWithIdOnly = await prisma.requestFile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RequestFileFindManyArgs>(args?: Prisma.SelectSubset<T, RequestFileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RequestFile.
   * @param {RequestFileCreateArgs} args - Arguments to create a RequestFile.
   * @example
   * // Create one RequestFile
   * const RequestFile = await prisma.requestFile.create({
   *   data: {
   *     // ... data to create a RequestFile
   *   }
   * })
   * 
   */
  create<T extends RequestFileCreateArgs>(args: Prisma.SelectSubset<T, RequestFileCreateArgs<ExtArgs>>): Prisma.Prisma__RequestFileClient<runtime.Types.Result.GetResult<Prisma.$RequestFilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RequestFiles.
   * @param {RequestFileCreateManyArgs} args - Arguments to create many RequestFiles.
   * @example
   * // Create many RequestFiles
   * const requestFile = await prisma.requestFile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RequestFileCreateManyArgs>(args?: Prisma.SelectSubset<T, RequestFileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RequestFiles and returns the data saved in the database.
   * @param {RequestFileCreateManyAndReturnArgs} args - Arguments to create many RequestFiles.
   * @example
   * // Create many RequestFiles
   * const requestFile = await prisma.requestFile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RequestFiles and only return the `id`
   * const requestFileWithIdOnly = await prisma.requestFile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RequestFileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RequestFileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestFilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RequestFile.
   * @param {RequestFileDeleteArgs} args - Arguments to delete one RequestFile.
   * @example
   * // Delete one RequestFile
   * const RequestFile = await prisma.requestFile.delete({
   *   where: {
   *     // ... filter to delete one RequestFile
   *   }
   * })
   * 
   */
  delete<T extends RequestFileDeleteArgs>(args: Prisma.SelectSubset<T, RequestFileDeleteArgs<ExtArgs>>): Prisma.Prisma__RequestFileClient<runtime.Types.Result.GetResult<Prisma.$RequestFilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RequestFile.
   * @param {RequestFileUpdateArgs} args - Arguments to update one RequestFile.
   * @example
   * // Update one RequestFile
   * const requestFile = await prisma.requestFile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RequestFileUpdateArgs>(args: Prisma.SelectSubset<T, RequestFileUpdateArgs<ExtArgs>>): Prisma.Prisma__RequestFileClient<runtime.Types.Result.GetResult<Prisma.$RequestFilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RequestFiles.
   * @param {RequestFileDeleteManyArgs} args - Arguments to filter RequestFiles to delete.
   * @example
   * // Delete a few RequestFiles
   * const { count } = await prisma.requestFile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RequestFileDeleteManyArgs>(args?: Prisma.SelectSubset<T, RequestFileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RequestFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestFileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RequestFiles
   * const requestFile = await prisma.requestFile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RequestFileUpdateManyArgs>(args: Prisma.SelectSubset<T, RequestFileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RequestFiles and returns the data updated in the database.
   * @param {RequestFileUpdateManyAndReturnArgs} args - Arguments to update many RequestFiles.
   * @example
   * // Update many RequestFiles
   * const requestFile = await prisma.requestFile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RequestFiles and only return the `id`
   * const requestFileWithIdOnly = await prisma.requestFile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RequestFileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RequestFileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestFilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RequestFile.
   * @param {RequestFileUpsertArgs} args - Arguments to update or create a RequestFile.
   * @example
   * // Update or create a RequestFile
   * const requestFile = await prisma.requestFile.upsert({
   *   create: {
   *     // ... data to create a RequestFile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RequestFile we want to update
   *   }
   * })
   */
  upsert<T extends RequestFileUpsertArgs>(args: Prisma.SelectSubset<T, RequestFileUpsertArgs<ExtArgs>>): Prisma.Prisma__RequestFileClient<runtime.Types.Result.GetResult<Prisma.$RequestFilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RequestFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestFileCountArgs} args - Arguments to filter RequestFiles to count.
   * @example
   * // Count the number of RequestFiles
   * const count = await prisma.requestFile.count({
   *   where: {
   *     // ... the filter for the RequestFiles we want to count
   *   }
   * })
  **/
  count<T extends RequestFileCountArgs>(
    args?: Prisma.Subset<T, RequestFileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RequestFileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RequestFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestFileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RequestFileAggregateArgs>(args: Prisma.Subset<T, RequestFileAggregateArgs>): Prisma.PrismaPromise<GetRequestFileAggregateType<T>>

  /**
   * Group by RequestFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RequestFileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RequestFileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RequestFileGroupByArgs['orderBy'] }
      : { orderBy?: RequestFileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RequestFileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRequestFileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RequestFile model
 */
readonly fields: RequestFileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RequestFile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RequestFileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  request<T extends Prisma.RequestDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RequestDefaultArgs<ExtArgs>>): Prisma.Prisma__RequestClient<runtime.Types.Result.GetResult<Prisma.$RequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RequestFile model
 */
export interface RequestFileFieldRefs {
  readonly id: Prisma.FieldRef<"RequestFile", 'String'>
  readonly requestId: Prisma.FieldRef<"RequestFile", 'String'>
  readonly fileUrl: Prisma.FieldRef<"RequestFile", 'String'>
  readonly fileType: Prisma.FieldRef<"RequestFile", 'String'>
  readonly createdAt: Prisma.FieldRef<"RequestFile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RequestFile findUnique
 */
export type RequestFileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestFile
   */
  select?: Prisma.RequestFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestFile
   */
  omit?: Prisma.RequestFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestFileInclude<ExtArgs> | null
  /**
   * Filter, which RequestFile to fetch.
   */
  where: Prisma.RequestFileWhereUniqueInput
}

/**
 * RequestFile findUniqueOrThrow
 */
export type RequestFileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestFile
   */
  select?: Prisma.RequestFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestFile
   */
  omit?: Prisma.RequestFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestFileInclude<ExtArgs> | null
  /**
   * Filter, which RequestFile to fetch.
   */
  where: Prisma.RequestFileWhereUniqueInput
}

/**
 * RequestFile findFirst
 */
export type RequestFileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestFile
   */
  select?: Prisma.RequestFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestFile
   */
  omit?: Prisma.RequestFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestFileInclude<ExtArgs> | null
  /**
   * Filter, which RequestFile to fetch.
   */
  where?: Prisma.RequestFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestFiles to fetch.
   */
  orderBy?: Prisma.RequestFileOrderByWithRelationInput | Prisma.RequestFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RequestFiles.
   */
  cursor?: Prisma.RequestFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RequestFiles.
   */
  distinct?: Prisma.RequestFileScalarFieldEnum | Prisma.RequestFileScalarFieldEnum[]
}

/**
 * RequestFile findFirstOrThrow
 */
export type RequestFileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestFile
   */
  select?: Prisma.RequestFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestFile
   */
  omit?: Prisma.RequestFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestFileInclude<ExtArgs> | null
  /**
   * Filter, which RequestFile to fetch.
   */
  where?: Prisma.RequestFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestFiles to fetch.
   */
  orderBy?: Prisma.RequestFileOrderByWithRelationInput | Prisma.RequestFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RequestFiles.
   */
  cursor?: Prisma.RequestFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RequestFiles.
   */
  distinct?: Prisma.RequestFileScalarFieldEnum | Prisma.RequestFileScalarFieldEnum[]
}

/**
 * RequestFile findMany
 */
export type RequestFileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestFile
   */
  select?: Prisma.RequestFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestFile
   */
  omit?: Prisma.RequestFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestFileInclude<ExtArgs> | null
  /**
   * Filter, which RequestFiles to fetch.
   */
  where?: Prisma.RequestFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RequestFiles to fetch.
   */
  orderBy?: Prisma.RequestFileOrderByWithRelationInput | Prisma.RequestFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RequestFiles.
   */
  cursor?: Prisma.RequestFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RequestFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RequestFiles.
   */
  skip?: number
  distinct?: Prisma.RequestFileScalarFieldEnum | Prisma.RequestFileScalarFieldEnum[]
}

/**
 * RequestFile create
 */
export type RequestFileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestFile
   */
  select?: Prisma.RequestFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestFile
   */
  omit?: Prisma.RequestFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestFileInclude<ExtArgs> | null
  /**
   * The data needed to create a RequestFile.
   */
  data: Prisma.XOR<Prisma.RequestFileCreateInput, Prisma.RequestFileUncheckedCreateInput>
}

/**
 * RequestFile createMany
 */
export type RequestFileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RequestFiles.
   */
  data: Prisma.RequestFileCreateManyInput | Prisma.RequestFileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RequestFile createManyAndReturn
 */
export type RequestFileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestFile
   */
  select?: Prisma.RequestFileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RequestFile
   */
  omit?: Prisma.RequestFileOmit<ExtArgs> | null
  /**
   * The data used to create many RequestFiles.
   */
  data: Prisma.RequestFileCreateManyInput | Prisma.RequestFileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestFileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RequestFile update
 */
export type RequestFileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestFile
   */
  select?: Prisma.RequestFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestFile
   */
  omit?: Prisma.RequestFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestFileInclude<ExtArgs> | null
  /**
   * The data needed to update a RequestFile.
   */
  data: Prisma.XOR<Prisma.RequestFileUpdateInput, Prisma.RequestFileUncheckedUpdateInput>
  /**
   * Choose, which RequestFile to update.
   */
  where: Prisma.RequestFileWhereUniqueInput
}

/**
 * RequestFile updateMany
 */
export type RequestFileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RequestFiles.
   */
  data: Prisma.XOR<Prisma.RequestFileUpdateManyMutationInput, Prisma.RequestFileUncheckedUpdateManyInput>
  /**
   * Filter which RequestFiles to update
   */
  where?: Prisma.RequestFileWhereInput
  /**
   * Limit how many RequestFiles to update.
   */
  limit?: number
}

/**
 * RequestFile updateManyAndReturn
 */
export type RequestFileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestFile
   */
  select?: Prisma.RequestFileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RequestFile
   */
  omit?: Prisma.RequestFileOmit<ExtArgs> | null
  /**
   * The data used to update RequestFiles.
   */
  data: Prisma.XOR<Prisma.RequestFileUpdateManyMutationInput, Prisma.RequestFileUncheckedUpdateManyInput>
  /**
   * Filter which RequestFiles to update
   */
  where?: Prisma.RequestFileWhereInput
  /**
   * Limit how many RequestFiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestFileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RequestFile upsert
 */
export type RequestFileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestFile
   */
  select?: Prisma.RequestFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestFile
   */
  omit?: Prisma.RequestFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestFileInclude<ExtArgs> | null
  /**
   * The filter to search for the RequestFile to update in case it exists.
   */
  where: Prisma.RequestFileWhereUniqueInput
  /**
   * In case the RequestFile found by the `where` argument doesn't exist, create a new RequestFile with this data.
   */
  create: Prisma.XOR<Prisma.RequestFileCreateInput, Prisma.RequestFileUncheckedCreateInput>
  /**
   * In case the RequestFile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RequestFileUpdateInput, Prisma.RequestFileUncheckedUpdateInput>
}

/**
 * RequestFile delete
 */
export type RequestFileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestFile
   */
  select?: Prisma.RequestFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestFile
   */
  omit?: Prisma.RequestFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestFileInclude<ExtArgs> | null
  /**
   * Filter which RequestFile to delete.
   */
  where: Prisma.RequestFileWhereUniqueInput
}

/**
 * RequestFile deleteMany
 */
export type RequestFileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RequestFiles to delete
   */
  where?: Prisma.RequestFileWhereInput
  /**
   * Limit how many RequestFiles to delete.
   */
  limit?: number
}

/**
 * RequestFile without action
 */
export type RequestFileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RequestFile
   */
  select?: Prisma.RequestFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RequestFile
   */
  omit?: Prisma.RequestFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestFileInclude<ExtArgs> | null
}
