
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  admin: 'admin',
  agent: 'agent',
  va: 'va'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const TemplateType = {
  residential: 'residential',
  commercial: 'commercial'
} as const

export type TemplateType = (typeof TemplateType)[keyof typeof TemplateType]


export const RequestStatus = {
  new: 'new',
  progress: 'progress',
  revision: 'revision',
  completed: 'completed'
} as const

export type RequestStatus = (typeof RequestStatus)[keyof typeof RequestStatus]
